import org.gradle.internal.impldep.com.fasterxml.jackson.core.JsonPointer.compile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.github.axet:kaptcha:0.0.9")
    implementation("org.springframework.boot:spring-boot-starter-web:2.7.4")
    implementation("org.springframework.boot:spring-boot-starter-aop:2.7.4")
    implementation("org.projectlombok:lombok:1.18.24")
    implementation("com.baomidou:mybatis-plus-boot-starter:3.5.1")
    implementation("org.springframework.boot:spring-boot-starter-security:2.7.4")
    implementation("org.springframework.boot:spring-boot-starter-data-redis:2.7.4")
    implementation("io.jsonwebtoken:jjwt-jackson:0.11.5")
    implementation("io.jsonwebtoken:jjwt-impl:0.11.5")
    implementation("io.jsonwebtoken:jjwt-api:0.11.5")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.7.4")
    implementation("org.springframework.boot:spring-boot-configuration-processor:2.7.4")
    implementation("org.springframework.boot:spring-boot-starter-amqp:2.7.4")
    implementation("org.springframework.boot:spring-boot-starter-data-elasticsearch:2.7.4")
    implementation("org.springframework.boot:spring-boot-starter-websocket:2.7.4")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.7.4")
    runtimeOnly("mysql:mysql-connector-java:8.0.30")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.4")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
}

group = "com.markethub"
version = "0.2.0-SNAPSHOT"
description = "vueblog"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
