# DataSource Config
spring:
  rabbitmq:
#    开启发送端确认
    publisher-confirm-type: correlated
#  开去发送端抵达队列的确认
    publisher-returns: true
#    只要抵达队列，以异步方式优先回调这个returnsConfirm
    template:
      mandatory: true
#    手动ack消息
#    只要没有手动确认，队列重的消息就不会在被消费后删除，下一次消费者进来再发给他
    listener:
      simple:
        acknowledge-mode: manual

  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8
server:
  port: 8081
  max-http-header-size: 10MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: off

vueblog:
  thread:
    core-size: 20
    max-size: 100
    keep-alive-time: 10

#logging:
#  level:
#    com.markerhub.mapper: debug
