# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    port: 6379
    password: 123456
    host: 127.0.0.1
  elasticsearch:
    username: elastic
    password: 123456
    uris: http://localhost:9200
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672


uploadPath: /users/mingchiuli/desktop/

imgFoldName: img

logging:
  config: classpath:logback-spring.xml

