# DataSource Config
spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8081
  max-http-header-size: 10MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

#logging:
#  level:
#    com.markerhub.mapper: debug

#logging:
#  level:
#    org.apache.catalina.core.ContainerBase: off
