# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allow&PublicKeyRetrieval=true
    username: root
    password: 12345678
  redis:
    port: 6379
    password: 123456
    host: 127.0.0.1
  elasticsearch:
    username: elastic
    password: 123456
    uris: http://localhost:9200
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672

logging:
  config: classpath:logback-spring.xml

vueblog:
  uploadPath: /users/mingchiuli/desktop/
  addResourceLocations: file:/users/mingchiuli/desktop/
  serverIpHost: 127.0.0.1
  jwt:
    secret: ti8n3439n439t43ld9nv9343ddfer09h
    #    七天
    expire: 604800
    header: Authorization



